#!/bin/sh

# Kill the IMTranscoderAgent process to ensure that any changes made by the tweak are reverted.
killall -9 IMTranscoderAgent

# Kill the com.apple.WebKit.WebContent process to ensure that any changes made by the tweak are reverted.
killall -9 com.apple.WebKit.WebContent

exit 0
